// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookClub.Models;

#nullable disable

namespace OnlineBookClub.Migrations
{
    [DbContext(typeof(OnlineBookClubContext))]
    [Migration("20250430061025_isread")]
    partial class isread
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineBookClub.Models.Answer_Record", b =>
                {
                    b.Property<int>("AR_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AR_Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("AnswerDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Learn_Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Pass")
                        .HasColumnType("bit");

                    b.Property<int>("Topic_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("times")
                        .HasColumnType("int");

                    b.HasKey("AR_Id")
                        .HasName("PK__Answer_R__003ED5F200B194C2");

                    b.HasIndex(new[] { "Learn_Id" }, "IX_Answer_Record_Learn_Id");

                    b.HasIndex(new[] { "User_Id" }, "IX_Answer_Record_User_Id");

                    b.ToTable("Answer_Record");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Book", b =>
                {
                    b.Property<int>("Book_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Book_Id"));

                    b.Property<string>("BookName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plan_Id")
                        .HasColumnType("int");

                    b.Property<string>("bookpath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Book_Id")
                        .HasName("PK__Book__C223F3B4CBA24285");

                    b.HasIndex(new[] { "Plan_Id" }, "IX_Book_Plan_Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("OnlineBookClub.Models.BookPlan", b =>
                {
                    b.Property<int>("Plan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Plan_Id"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Plan_Goal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Plan_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plan_Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plan_suject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Plan_Id")
                        .HasName("PK__BookPlan__9BAF9B031DE0303A");

                    b.HasIndex(new[] { "User_Id" }, "IX_BookPlan_User_Id");

                    b.ToTable("BookPlan");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Learn", b =>
                {
                    b.Property<int>("Learn_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Learn_Id"));

                    b.Property<DateTime>("DueTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Learn_Index")
                        .HasColumnType("int");

                    b.Property<string>("Learn_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Manual_Check")
                        .HasColumnType("bit");

                    b.Property<double>("Pass_Standard")
                        .HasColumnType("float");

                    b.Property<int>("Plan_Id")
                        .HasColumnType("int");

                    b.HasKey("Learn_Id")
                        .HasName("PK__Learn__319993005E050ACF");

                    b.HasIndex(new[] { "Plan_Id" }, "IX_Learn_Plan_Id");

                    b.ToTable("Learn");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Members", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("User_Id")
                        .HasName("PK__Members__206D9170C8FFF617");

                    b.HasIndex(new[] { "Email" }, "UQ__Members__A9D10534555AED53")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Notice", b =>
                {
                    b.Property<int>("Notice_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notice_Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NoticeTime")
                        .HasColumnType("datetime");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Notice_Id")
                        .HasName("PK__Notice__E9930CABD96445D5");

                    b.HasIndex(new[] { "User_Id" }, "IX_Notice_User_Id");

                    b.ToTable("Notice");
                });

            modelBuilder.Entity("OnlineBookClub.Models.PlanMembers", b =>
                {
                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("Plan_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("User_Id", "Plan_Id")
                        .HasName("PK__PlanMemb__09D768C06B5D99B1");

                    b.HasIndex(new[] { "Plan_Id" }, "IX_PlanMembers_Plan_Id");

                    b.ToTable("PlanMembers");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Post", b =>
                {
                    b.Property<int>("Post_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Post_Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Img_Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Plan_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Post_Id")
                        .HasName("PK__Post__5875F7AD1838C391");

                    b.HasIndex(new[] { "Plan_Id" }, "IX_Post_Plan_Id");

                    b.HasIndex(new[] { "User_Id" }, "IX_Post_User_Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Post_Report", b =>
                {
                    b.Property<int>("P_Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_Report_Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("未審核");

                    b.Property<int>("Post_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Report_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Report_text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("P_Report_Id")
                        .HasName("PK__Post_Rep__AF4E25E3E831EA16");

                    b.HasIndex(new[] { "Post_Id" }, "IX_Post_Report_Post_Id");

                    b.ToTable("Post_Report");
                });

            modelBuilder.Entity("OnlineBookClub.Models.ProgressTracking", b =>
                {
                    b.Property<int>("Progress_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Progress_Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Learn_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Progress_Id")
                        .HasName("PK__Progress__D558797A60C7671D");

                    b.HasIndex(new[] { "Learn_Id" }, "IX_ProgressTracking_Learn_Id");

                    b.HasIndex(new[] { "User_Id" }, "IX_ProgressTracking_User_Id");

                    b.ToTable("ProgressTracking");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Reply", b =>
                {
                    b.Property<int>("Reply_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Reply_Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Post_Id")
                        .HasColumnType("int");

                    b.Property<string>("ReplyContent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReplyImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReplyTime")
                        .HasColumnType("datetime");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Reply_Id")
                        .HasName("PK__Reply__B6633284E3C88026");

                    b.HasIndex(new[] { "Post_Id" }, "IX_Reply_Post_Id");

                    b.HasIndex(new[] { "User_Id" }, "IX_Reply_User_Id");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Reply_Report", b =>
                {
                    b.Property<int>("R_Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("R_Report_Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("未審核");

                    b.Property<int>("Reply_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Report_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Report_text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("R_Report_Id")
                        .HasName("PK__Reply_Re__6B66990FED16DBBA");

                    b.HasIndex(new[] { "Reply_Id" }, "IX_Reply_Report_Reply_Id");

                    b.ToTable("Reply_Report");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Statistic", b =>
                {
                    b.Property<int>("Statistics_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Statistics_Id"));

                    b.Property<int>("CopyCount")
                        .HasColumnType("int");

                    b.Property<int>("Plan_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserCount")
                        .HasColumnType("int");

                    b.Property<int>("ViewTimes")
                        .HasColumnType("int");

                    b.HasKey("Statistics_Id")
                        .HasName("PK__Statisti__A2EC2FD9D49FAB21");

                    b.HasIndex(new[] { "Plan_Id" }, "IX_Statistic_Plan_Id");

                    b.ToTable("Statistic");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Topic", b =>
                {
                    b.Property<int>("Topic_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Topic_Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Learn_Id")
                        .HasColumnType("int");

                    b.Property<string>("Option_A")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Option_B")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Option_C")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Option_D")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Question_Id")
                        .HasColumnType("int");

                    b.HasKey("Topic_Id")
                        .HasName("PK__Topic__8DEAA40577172212");

                    b.HasIndex(new[] { "Learn_Id" }, "IX_Topic_Learn_Id");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Answer_Record", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Learn", "Learn")
                        .WithMany("Answer_Record")
                        .HasForeignKey("Learn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Answer_Re__Learn__60A75C0F");

                    b.HasOne("OnlineBookClub.Models.Members", "User")
                        .WithMany("Answer_Record")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK__Answer_Re__User___5FB337D6");

                    b.Navigation("Learn");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Book", b =>
                {
                    b.HasOne("OnlineBookClub.Models.BookPlan", "Plan")
                        .WithMany("Book")
                        .HasForeignKey("Plan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book__Plan_Id__5629CD9C");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("OnlineBookClub.Models.BookPlan", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Members", "User")
                        .WithMany("BookPlan")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK__BookPlan__User_I__4CA06362");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Learn", b =>
                {
                    b.HasOne("OnlineBookClub.Models.BookPlan", "Plan")
                        .WithMany("Learn")
                        .HasForeignKey("Plan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Learn__Plan_Id__59063A47");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Notice", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Members", "User")
                        .WithMany("Notice")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK__Notice__User_Id__534D60F1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookClub.Models.PlanMembers", b =>
                {
                    b.HasOne("OnlineBookClub.Models.BookPlan", "Plan")
                        .WithMany("PlanMembers")
                        .HasForeignKey("Plan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PlanMembe__Plan___70DDC3D8");

                    b.HasOne("OnlineBookClub.Models.Members", "User")
                        .WithMany("PlanMembers")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK__PlanMembe__User___6FE99F9F");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Post", b =>
                {
                    b.HasOne("OnlineBookClub.Models.BookPlan", "Plan")
                        .WithMany("Post")
                        .HasForeignKey("Plan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Post__Plan_Id__4F7CD00D");

                    b.HasOne("OnlineBookClub.Models.Members", "User")
                        .WithMany("Post")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK__Post__User_Id__5070F446");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Post_Report", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Post", "Post")
                        .WithMany("Post_Report")
                        .HasForeignKey("Post_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Post_Repo__Post___6C190EBB");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("OnlineBookClub.Models.ProgressTracking", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Learn", "Learn")
                        .WithMany("ProgressTracking")
                        .HasForeignKey("Learn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProgressT__Learn__6477ECF3");

                    b.HasOne("OnlineBookClub.Models.Members", "User")
                        .WithMany("ProgressTracking")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK__ProgressT__User___6383C8BA");

                    b.Navigation("Learn");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Reply", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Post", "Post")
                        .WithMany("Reply")
                        .HasForeignKey("Post_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reply__Post_Id__5BE2A6F2");

                    b.HasOne("OnlineBookClub.Models.Members", "User")
                        .WithMany("Reply")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK__Reply__User_Id__5CD6CB2B");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Reply_Report", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Reply", "Reply")
                        .WithMany("Reply_Report")
                        .HasForeignKey("Reply_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reply_Rep__Reply__68487DD7");

                    b.Navigation("Reply");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Statistic", b =>
                {
                    b.HasOne("OnlineBookClub.Models.BookPlan", "Plan")
                        .WithMany("Statistic")
                        .HasForeignKey("Plan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Statistic__Plan___76969D2E");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Topic", b =>
                {
                    b.HasOne("OnlineBookClub.Models.Learn", "Learn")
                        .WithMany("Topic")
                        .HasForeignKey("Learn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Topic__Learn_Id__73BA3083");

                    b.Navigation("Learn");
                });

            modelBuilder.Entity("OnlineBookClub.Models.BookPlan", b =>
                {
                    b.Navigation("Book");

                    b.Navigation("Learn");

                    b.Navigation("PlanMembers");

                    b.Navigation("Post");

                    b.Navigation("Statistic");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Learn", b =>
                {
                    b.Navigation("Answer_Record");

                    b.Navigation("ProgressTracking");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Members", b =>
                {
                    b.Navigation("Answer_Record");

                    b.Navigation("BookPlan");

                    b.Navigation("Notice");

                    b.Navigation("PlanMembers");

                    b.Navigation("Post");

                    b.Navigation("ProgressTracking");

                    b.Navigation("Reply");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Post", b =>
                {
                    b.Navigation("Post_Report");

                    b.Navigation("Reply");
                });

            modelBuilder.Entity("OnlineBookClub.Models.Reply", b =>
                {
                    b.Navigation("Reply_Report");
                });
#pragma warning restore 612, 618
        }
    }
}
